In [317]:
import numpy as np
import pandas as pd
import scipy
import math
import statsmodels
import matplotlib.pyplot as plt
import datetime
import seaborn as sns
from WindPy import w
import calendar
import numpy as np
import scipy.stats as stats
from sklearn import linear_model
import statsmodels.api as sm
from statsmodels.sandbox.regression.predstd import wls_prediction_std
%matplotlib inline

# 1. 股票

In [318]:
symbol = "881001.WI"

### 某一个时间点的财务类指标

In [359]:
factors = ["mkt_cap_ard", # 总市值
           "pe_ttm", # 市盈率
           "pcf_ocf_ttm", # 市现率
           "dividendyield2", # 股息率
           "profit_ttm", # 净利润
           "or_ttm", # 营业收入
           "ps_ttm" # 市销率
          ]

In [360]:
raw_data = w.wss(symbol, factors, "tradeDate=%s"%("20161231"))

In [361]:
raw_data

.ErrorCode=0
.Codes=[881001.WI]
.Fields=[MKT_CAP_ARD,PE_TTM,PCF_OCF_TTM,DIVIDENDYIELD2,PROFIT_TTM,OR_TTM,PS_TTM]
.Times=[20170214 16:18:47]
.Data=[[5.55866103453e+13],[21.3956],[9.0345],[1.315],[5570825205.05],[28950105416.0],[1.8079]]

In [344]:
dic = {}
for data, field in zip(raw_data.Data, raw_data.Fields):
    dic[str(field.lower())] = data

In [345]:
dic

{'dividendyield2': [1.315],
 'mkt_cap_ard': [55586610345291.01],
 'or_ttm': [28950105415.99],
 'pcf_ocf_ttm': [9.0345],
 'pe_ttm': [21.3956],
 'profit_ttm': [5570825205.05]}

# 获取历史财务数据

In [353]:
current_date = datetime.datetime(2016, 12, 20)
end_date = datetime.datetime(2016, 12, 31)
dic = {}
dates = []
while current_date <= end_date:
    print current_date.strftime("%Y%m%d")
    raw_data = w.wss(symbol, factors, "tradeDate=%s"%(current_date.strftime("%Y%m%d")))
    for data, field in zip(raw_data.Data, raw_data.Fields):
        if not dic.has_key(str(field.lower())):
            dic[str(field.lower())] = data
        else:
            dic[str(field.lower())].append(data[0])
    dates.append(current_date)
    current_date = current_date + datetime.timedelta(1)

20161201
20161202
20161203
20161204
20161205
20161206
20161207
20161208
20161209
20161210
20161211
20161212
20161213
20161214
20161215
20161216
20161217
20161218
20161219
20161220
20161221
20161222
20161223
20161224
20161225
20161226
20161227
20161228
20161229
20161230
20161231

In [354]:
df = pd.DataFrame(dic, index=dates)

In [355]:
df

,dividendyield2,mkt_cap_ard,or_ttm,pcf_ocf_ttm,pe_ttm,profit_ttm
2016-12-01,1.2517,5.843253e+13,NaN,9.4877,22.5466,NaN
2016-12-02,1.2669,5.779511e+13,NaN,9.3842,22.3072,NaN
2016-12-03,1.2670,5.779568e+13,NaN,9.3843,22.2995,NaN
2016-12-04,1.2670,5.779568e+13,NaN,9.3843,22.2995,NaN
2016-12-05,1.2798,5.723238e+13,NaN,9.2928,22.0822,NaN
2016-12-06,1.2787,5.724443e+13,NaN,9.3126,22.0773,NaN
2016-12-07,1.2683,5.767802e+13,NaN,9.3830,22.2483,NaN
2016-12-08,1.2738,5.749537e+13,NaN,9.3530,22.1709,NaN
2016-12-09,1.2725,5.768293e+13,NaN,9.3833,22.2414,NaN
2016-12-10,1.2725,5.768290e+13,NaN,9.3833,22.2414,NaN
2016-12-11,1.2725,5.768290e+13,NaN,9.3833,22.2414,NaN
2016-12-12,1.3186,5.579888e+13,NaN,9.0766,21.5141,NaN
2016-12-13,1.3157,5.586930e+13,NaN,9.0871,21.5377,NaN
2016-12-14,1.3250,5.555802e+13,NaN,9.0363,21.4168,NaN
2016-12-15,1.3262,5.538905e+13,NaN,9.0087,21.3510,NaN
2016-12-16,1.3186,5.566610e+13,NaN,9.0527,21.4500,NaN
2016-12-17,1.3127,5.566667e+13,NaN,9.0528,21.4503,NaN
2016-12-18,1.3127,5.566667e+13,NaN,9.0528,21.4503,NaN
2016-12-19,1.3157,5.554824e+13,NaN,9.0330,21.4035,NaN
2016-12-20,1.3199,5.535844e+13,NaN,9.0018,21.3279,NaN
2016-12-21,1.3069,5.591413e+13,NaN,9.0919,21.5406,NaN
2016-12-22,1.3067,5.592158e+13,NaN,9.0931,21.5429,NaN
2016-12-23,1.3183,5.544383e+13,NaN,9.0150,21.3566,NaN
2016-12-24,1.3184,5.544384e+13,NaN,9.0150,21.3567,NaN
2016-12-25,1.3184,5.544384e+13,NaN,9.0150,21.3567,NaN
2016-12-26,1.3124,5.570349e+13,NaN,9.0564,21.4532,NaN
2016-12-27,1.3123,5.569321e+13,NaN,9.0538,21.4463,NaN
2016-12-28,1.3164,5.552185e+13,NaN,9.0245,21.3733,NaN
2016-12-29,1.3182,5.543445e+13,NaN,9.0101,21.3384,NaN
2016-12-30,1.3151,5.558429e+13,NaN,9.0342,21.3947,NaN
2016-12-31,1.3150,5.558661e+13,2.895011e+10,9.0345,21.3956,5.570825e+09